parameters: {}
environment: {}
packages:
  - name: image
    environment: {}
    parameters: {}
    actions:
      - name: resize
        main: ''
        runtime: 'nodejs:default'
        parameters: {}
        environment: {}
